name: deploy blog to github pages
on: 
  push: 
  workflow_dispatch:

jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps: 
      - name: checkout
        uses: actions/checkout@v6

      - name: build
        run: |
          npm ci
          npm run docs:build

      - name: deploy2
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git checkout -b test
          mv .vitepress/dist dist
          rm .github -r
          git add .
          git commit -m "test"
          push --force https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/liuzuwei-go/liuzuwei-go.github.io.git test:main

      # - name: deploy
      #   uses: liuzuwei-go/deploy@master
      #   with: 
      #     folder: .vitepress/dist
      #     repository-name: liuzuwei-go/liuzuwei-go.github.io
      #     token: ${{ secrets.DEPLOY_TOKEN }}
      #     single-commit: true