name: deploy blog to github pages
on: 
  push: 
  workflow_dispatch:

jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps: 
      - name: checkout
        uses: actions/checkout@v6

      - name: build
        run: |
          npm ci
          npm run docs:build

      - name: deploy
        uses: liuzuwei-go/deploy@master
        with: 
          folder: .vitepress/dist
          repository-name: liuzuwei-go/liuzuwei-go.github.io
          token: ${{ secrets.DEPLOY_TOKEN }}
          single-commit: true